### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by Fwinter1** [ayared/Live-Specgram#2]
Matplotlib will boot the spectogram for what seems like one frame, but then the shell gives this error:

`Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\cbook\__init__.py", line 216, in process
    func(*args, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 953, in _start
    self._init_draw()
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1732, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "C:\Program Files\Python36\lib\site-packages\matplotlib\animation.py", line 1755, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "F:\4 Libraries\Documents\Python\click\Live-Specgram-master\run_specgram.py", line 58, in update_fig
    data = get_sample(stream,pa)
NameError: name 'stream' is not defined`

Not sure what root cause is.

**Comment by Fwinter1** [comment]
Seems to be due to my using of a newer matplotlib version, as 1.4.3 will not install on my system :(

**Comment by piratos** [comment]
probably a bit late but I tweaked the run_specgram script to work on uptodate packages
https://gist.github.com/piratos/185d08494f365c5f95a54706abc72fa4
